import { z } from "zod";

export const foodWords = [
  "apple",
  "apricot",
  "avocado",
  "bacon",
  "banana",
  "barley",
  "basil",
  "bean",
  "beetroot",
  "berry",
  "biscuit",
  "bread",
  "burger",
  "butter",
  "buttered",
  "cake",
  "carrot",
  "cashew",
  "cheese",
  "cherry",
  "chicken",
  "chickpea",
  "chunky",
  "creamy",
  "crispy",
  "crunchy",
  "crusty",
  "cucumber",
  "curry",
  "custard",
  "date",
  "delicious",
  "dough",
  "dumpling",
  "egg",
  "fig",
  "fish",
  "flour",
  "fluffy",
  "fresh",
  "fruity",
  "garlic",
  "ginger",
  "glazed",
  "golden",
  "grape",
  "gravy",
  "grilled",
  "hearty",
  "honey",
  "jam",
  "juice",
  "juicy",
  "kale",
  "lamb",
  "leek",
  "lemon",
  "lentil",
  "lime",
  "mango",
  "melon",
  "milk",
  "mint",
  "minty",
  "mushroom",
  "noodle",
  "nutty",
  "oat",
  "olive",
  "onion",
  "orange",
  "pancake",
  "pasta",
  "pastry",
  "peach",
  "peanut",
  "pear",
  "pepper",
  "pie",
  "pineapple",
  "plum",
  "popcorn",
  "potato",
  "prawn",
  "pudding",
  "pumpkin",
  "radish",
  "rice",
  "rich",
  "ripe",
  "roast",
  "roasted",
  "salad",
  "salt",
  "salty",
  "sandwich",
  "sauce",
  "sausage",
  "seed",
  "silky",
  "smoky",
  "smooth",
  "soup",
  "spicy",
  "spinach",
  "stew",
  "sticky",
  "sugar",
  "sweet",
  "syrup",
  "tangy",
  "tart",
  "tasty",
  "tea",
  "tender",
  "toast",
  "toasted",
  "tomato",
  "turnip",
  "walnut",
  "warm",
  "wheat",
  "wrap",
  "zesty",
] as const;

const wordsPerSlug = 4;

export const slugSchema = z.string().regex(/^[a-z]+(-[a-z]+){3}$/, {
  message: "A Slug is four lowercase words joined by dashes",
});

export type Slug = z.infer<typeof slugSchema>;

const takeOne = (from: string[], random: () => number): string => {
  const index = Math.min(Math.floor(random() * from.length), from.length - 1);
  const [word] = from.splice(index, 1);
  if (word === undefined) throw new Error("The food wordlist ran dry");
  return word;
};

export const generateSlug = (random: () => number): Slug => {
  const remaining: string[] = [...foodWords];
  const words = Array.from({ length: wordsPerSlug }, () =>
    takeOne(remaining, random),
  );
  return words.join("-");
};
